#!/usr/bin/env python3
"""Parse Procedures.xlsx and generate seed SQL for section_descriptions, procedure_items (control questions), and procedure_evidence_items."""
import openpyxl, re, uuid, json, sys

import os.path
_script_dir = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(_script_dir, '..', '..', 'Procedures.xlsx')
OUT = os.path.join(_script_dir, '..', 'internal', 'db', 'seed_procedures.sql')

def split_evidence(text):
    """Split evidence text into sub-items if numbered. Returns list of (sub_label, evidence_text)."""
    lines = text.strip().split('\n')
    lines = [l.strip() for l in lines if l.strip()]
    if not lines:
        return []
    if len(lines) <= 1:
        return [(None, lines[0])]
    numbered = []
    for line in lines:
        m = re.match(r'^(\d+(?:\.\d+)?)[.)]?\s+(.*)', line)
        if m:
            numbered.append((m.group(1), m.group(2).strip()))
    if numbered and len(numbered) == len(lines):
        return numbered
    return [(None, text.strip())]

def esc(val):
    """Escape string for SQL (single-quote doubling)."""
    return val.replace("'", "''")

def sql_esc(val):
    if val is None:
        return 'NULL'
    return "'" + esc(val) + "'"

wb = openpyxl.load_workbook(SRC)
ws = wb.active
rows = list(ws.iter_rows(min_row=8, values_only=True))
data = []

current_section_num = None
current_section_desc_lines = []
current_control_num = 0

for vals in rows:
    col_b = str(vals[1]).strip() if len(vals) > 1 and vals[1] else ''
    col_k = str(vals[10]).strip() if len(vals) > 10 and vals[10] else ''
    col_l = str(vals[11]).strip() if len(vals) > 11 and vals[11] else ''
    if not col_b and not col_k:
        continue
    sm = re.match(r'^(\d+)\.\s', col_b)
    if sm and col_k:
        if current_section_num is not None:
            data.append({'type': 'section_desc', 'num': current_section_num, 'desc': '\n\n'.join(current_section_desc_lines)})
        current_section_num = int(sm.group(1))
        current_section_desc_lines = [col_b]
        current_control_num = 0
        current_control_num += 1
        ctrl = {'type': 'control', 'section_num': current_section_num, 'control_num': current_control_num, 'text': col_k}
        ev_parts = split_evidence(col_l)
        for label, ev_text in ev_parts:
            ctrl.setdefault('evidences', []).append({'label': label, 'text': ev_text})
        data.append(ctrl)
    elif col_b and not col_k and current_section_num:
        current_section_desc_lines.append(col_b)
    elif col_k and current_section_num:
        current_control_num += 1
        ctrl = {'type': 'control', 'section_num': current_section_num, 'control_num': current_control_num, 'text': col_k}
        ev_parts = split_evidence(col_l)
        for label, ev_text in ev_parts:
            ctrl.setdefault('evidences', []).append({'label': label, 'text': ev_text})
        data.append(ctrl)

if current_section_num is not None:
    data.append({'type': 'section_desc', 'num': current_section_num, 'desc': '\n\n'.join(current_section_desc_lines)})

# Generate stable UUIDs
section_uuids = {}
section_num_map = {}
control_uuids = {}
evidence_uuids = []

for d in data:
    if d['type'] == 'section_desc':
        u = uuid.uuid5(uuid.NAMESPACE_DNS, f"section_{d['num']}")
        section_uuids[d['num']] = u
        section_num_map[d['num']] = d['desc']
    elif d['type'] == 'control':
        u = uuid.uuid5(uuid.NAMESPACE_DNS, f"control_{d['section_num']}_{d['control_num']}_{d['text'][:80]}")
        control_uuids[(d['section_num'], d['control_num'])] = u
        for i, ev in enumerate(d.get('evidences', [])):
            label = ev['label'] or f"ev_{i}"
            eu = uuid.uuid5(uuid.NAMESPACE_DNS, f"evidence_{d['section_num']}_{d['control_num']}_{label}_{ev['text'][:80]}")
            evidence_uuids.append({'uuid': eu, 'section_num': d['section_num'], 'control_num': d['control_num'], 'label': ev['label'], 'text': ev['text'], 'sort_order': i})

section_names = {
    1: 'Leadership', 2: 'Policy', 3: 'General Requirements', 4: 'Operational Risk Management',
    5: 'Compliance Obligations', 6: 'Objectives, Targets and Programmes', 7: 'Stakeholder Management',
    8: 'Competencies, Awareness & Training', 9: 'Operational Planning and Control',
    10: 'Document, Data and Records Management', 11: 'Product Lifecycle Management',
    12: 'Interface Management', 13: 'Occurrence & Non-Conformity Management',
    14: 'Contractor Management', 15: 'Integrated Assurance', 16: 'Business Continuity Management',
    17: 'Human Factors Management', 18: 'Continual improvement'
}

# Write SQL
lines = []
lines.append("-- Generated by scripts/parse_procedures.py")
lines.append("-- Section descriptions, control questions (procedure_items), and evidence items")
lines.append("")

# Section descriptions
lines.append("-- Clear existing data (order matters due to FKs)")
lines.append("DELETE FROM audit_procedure_responses;")
lines.append("DELETE FROM procedure_evidence_items;")
lines.append("DELETE FROM procedure_items;")
lines.append("DELETE FROM section_descriptions;")
lines.append("")

lines.append("-- Reseed identity / sequences if any")
lines.append("")

lines.append("-- Section Descriptions")
for sn in sorted(section_uuids.keys()):
    desc = section_num_map[sn]
    lines.append(f"INSERT INTO section_descriptions (id, section_number, description) VALUES ({sql_esc(str(section_uuids[sn]))}, {sn}, {sql_esc(desc)});")
lines.append("")

# Control questions (procedure_items)
lines.append("-- Procedure Items (control questions)")
for key in sorted(control_uuids.keys(), key=lambda k: (k[0], k[1])):
    sn, cn = key
    cu = control_uuids[key]
    text = ''
    for d in data:
        if d.get('type') == 'control' and d['section_num'] == sn and d['control_num'] == cn:
            text = d['text']
            break
    name = section_names.get(sn, f'Section {sn}')
    lines.append(f"INSERT INTO procedure_items (id, section_number, section_name, control_question, evidence_required, tims_ref, sort_order) VALUES ({sql_esc(str(cu))}, {sn}, {sql_esc(name)}, {sql_esc(text)}, '', '', {sn * 100 + cn});")
lines.append("")

# Evidence items
lines.append("-- Evidence Items")
for ev in evidence_uuids:
    pu = control_uuids[(ev['section_num'], ev['control_num'])]
    label = ev['label'] or ''
    lines.append(f"INSERT INTO procedure_evidence_items (id, procedure_item_id, evidence_text, sub_label, sort_order) VALUES ({sql_esc(str(ev['uuid']))}, {sql_esc(str(pu))}, {sql_esc(ev['text'])}, {sql_esc(label)}, {ev['sort_order']});")
lines.append("")

# Update audit_procedure_responses table structure (run separately)
lines.append("-- Run migration 016 separately to modify audit_procedure_responses")

out = '\n'.join(lines)
with open(OUT, 'w') as f:
    f.write(out)

print(f"Generated {OUT}")
print(f"Sections: {len(section_uuids)}")
print(f"Controls: {len(control_uuids)}")
print(f"Evidence items: {len(evidence_uuids)}")
