CREATE TABLE findings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    audit_id UUID NOT NULL REFERENCES audits(id) ON DELETE CASCADE,
    auditor_id UUID NOT NULL REFERENCES users(id),
    ncr_ref TEXT NOT NULL,
    date_raised DATE NOT NULL DEFAULT CURRENT_DATE,
    raised_by_name TEXT NOT NULL DEFAULT '',
    raised_by_sap_no TEXT NOT NULL DEFAULT '',
    contact_details TEXT NOT NULL DEFAULT '',
    origin_legal BOOLEAN NOT NULL DEFAULT FALSE,
    origin_system BOOLEAN NOT NULL DEFAULT FALSE,
    origin_other BOOLEAN NOT NULL DEFAULT FALSE,
    type_env BOOLEAN NOT NULL DEFAULT FALSE,
    type_health BOOLEAN NOT NULL DEFAULT FALSE,
    type_railway_safety BOOLEAN NOT NULL DEFAULT FALSE,
    type_customer_complaint BOOLEAN NOT NULL DEFAULT FALSE,
    type_fire BOOLEAN NOT NULL DEFAULT FALSE,
    type_maritime BOOLEAN NOT NULL DEFAULT FALSE,
    type_vendor BOOLEAN NOT NULL DEFAULT FALSE,
    type_system_ncr BOOLEAN NOT NULL DEFAULT FALSE,
    type_hazmat BOOLEAN NOT NULL DEFAULT FALSE,
    type_quality BOOLEAN NOT NULL DEFAULT FALSE,
    type_audit BOOLEAN NOT NULL DEFAULT FALSE,
    item_no TEXT NOT NULL DEFAULT '',
    serial_batch_no TEXT NOT NULL DEFAULT '',
    customer_name TEXT NOT NULL DEFAULT '',
    vendor_name TEXT NOT NULL DEFAULT '',
    vendor_no TEXT NOT NULL DEFAULT '',
    contravened_clause TEXT NOT NULL DEFAULT '',
    priority TEXT NOT NULL DEFAULT 'Observation' CHECK (priority IN ('Major', 'Minor', 'Area of Concern', 'Observation')),
    area_of_concern TEXT NOT NULL DEFAULT '',
    resp_person_int_name TEXT NOT NULL DEFAULT '',
    resp_person_int_sap TEXT NOT NULL DEFAULT '',
    resp_person_ext_name TEXT NOT NULL DEFAULT '',
    raised_by_business_id UUID REFERENCES businesses(id),
    raised_against_business_id UUID REFERENCES businesses(id),
    description TEXT NOT NULL DEFAULT '',
    work_type_process TEXT NOT NULL DEFAULT '',
    immediate_action_taken BOOLEAN NOT NULL DEFAULT FALSE,
    action_agreed_approved BOOLEAN NOT NULL DEFAULT FALSE,
    stop_certificate_issued BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE finding_photos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    finding_id UUID NOT NULL REFERENCES findings(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
